### PR TITLE
Upgrade to hathora 0.9.0

### PR DESCRIPTION
**Pull request by hpx7**
In Hathora 0.9.0, custom frontends specify their own start and build scripts

### CODE REVIEW

**Comment by supertommy** [comment]
the Cloudflare build seems to be failing because it can't find the output directory but I've tried it locally and it is in the same place: `dist/client/web`

**Comment by supertommy** [comment]
logs: [flappy-bird-hathora.b4b88094-228b-442b-8fd0-24d694a127b3.log](https://github.com/ourcade/flappy-bird-hathora/files/8880107/flappy-bird-hathora.b4b88094-228b-442b-8fd0-24d694a127b3.log)

**Comment by hpx7** [comment]
That's changed in 0.9.0: the dist is now in `client/web/dist` instead

**Comment by hpx7** [comment]
(make sure you upgrade the hathora cli locally)

**Comment by supertommy** [comment]
oh right, forgot to update locally 😅

**Review by supertommy — APPROVED** [review]

**Pull request merged**
